patreon:
  patreon_enabled:
    default: false
    client: true
  patreon_client_id:
    default: ''
    secret: true
  patreon_client_secret:
    default: ''
    secret: true
  patreon_creator_access_token:
    default: ''
    secret: true
  patreon_creator_refresh_token:
    default: ''
    secret: true
  patreon_campaign_url:
    default: ''
    client: true
  patreon_campaign_id:
    default: ''
    hidden: true
  patreon_cache_duration:
    default: 30
    min: 5
    max: 1440
  patreon_sync_frequency:
    default: 24
    min: 1
    max: 168
