patreon_donations:
  patreon_donations_enabled:
    default: false
    client: true
  patreon_donations_api_version:
    default: 'v2'
    type: enum
    choices:
      - v1
      - v2
    client: true
  patreon_donations_campaign_url:
    default: ''
    client: true
  patreon_donations_campaign_id:
    default: ''
    hidden: true
  patreon_donations_platform_fee_percentage:
    default: 10.0
    min: 0
    max: 100
    type: float
    client: true
  patreon_donations_tax_rate_percentage:
    default: 43.0
    min: 0
    max: 100
    type: float
    client: true
  patreon_donations_allowed_groups:
    type: group_list
    default: "admins"
    list_type: compact
    client: true
  patreon_donations_cache_duration:
    default: 6
    min: 1
    max: 24
  patreon_donations_sync_frequency:
    default: 24
    min: 1
    max: 168
